---
- hosts: master
  vars:
    ImageName: ""
    Namespace: ""
    imageTag: ""
    ansible_python_interpreter:  /usr/bin/python3
  remote_user: irfanshaikh
  become: yes
  tasks:
    - name: Install Docker SDK for Python
      pip:
       name: "docker<5" 
      become: yes
    - name: Build an image and push it to a private repo
      docker_image:
       build:
        path: /opt/uat/src/
       name: registry.devops4u.xyz/pythonapp7:v1
       tag: v1
       push: yes
       source: build
      vars:
        ansible_python_interpreter:  /usr/bin/python3    
    - name:  DEPLOYMENT STATUS
      become_user: root
      shell: sudo kubectl get deployment,pods,rs 
      register: getdeploy
    - debug: msg="{{ getdeploy.stdout_lines }}"
    - name: Search for all running pods
      kubernetes.core.k8s_info:
          kind: Pod
          field_selectors:
            - status.phase=Running
      register: listpodd
    - debug:
        msg: "{{ listpodd }}"

