---
- hosts: master
  vars:
    imagename: ""
    namespace: ""
    imageTag: ""
    ansible_python_interpreter:  /usr/bin/python3
  remote_user: devops
  become: yes
  tasks:
    - name: "Docker file copy"
      become_user: root
      copy:
        src: /var/lib/jenkins/workspace/ansiblejob/
        dest: /opt/uat/
    - name: Install Docker SDK for Python
      pip:
       name: "docker<5" 
      become: yes
    - name: Build an image and push it to a private repo
      docker_image:
       build:
        path: /opt/uat/src/
       name: registry.devops4u.xyz/pythonapp10:v1
       tag: v1
       push: yes
       source: build
      vars:
        ansible_python_interpreter:  /usr/bin/python3 
    - name:  DEPLOYINGPYTHON APP
      become_user: root
      shell: kubectl apply -f /opt/uat/src/python-devlopment.yaml --record=true
      register: deployment
    - debug: msg="{{ deployment.stdout_lines }}"
    - name:  DEPLOYMENT STATUS
      become_user: root
      shell: sudo kubectl get deployment,pods,rs &&  kubectl describe deploy pythonapp-deployment | tail
      register: getdeploy
    - debug: msg="{{ getdeploy.stdout_lines }}"
    - name:  DEPLOYMENT STATUS
      become_user: root
      shell: sleep 15 && sudo kubectl get deployment,pods,rs  &&  kubectl describe deploy pythonapp-deployment | tail
      register: getdeploy
    - debug: msg="{{ getdeploy.stdout_lines }}"
    
    


