---
- hosts: master
  vars:
    imagename: ""
    namespace: ""
    imageTag: ""
    ansible_python_interpreter:  /usr/bin/python3
  remote_user: irfanshaikh
  become: yes
  tasks:
    - name: "Docker file copy"
      become_user: root
      copy:
        src: /Users/devops/devops/src 
        dest: /opt/uat/ 
    - name: Install Docker SDK for Python
      pip:
       name: "docker<5" 
      become: yes
    - name: Build an image and push it to a private repo
      docker_image:
       build:
        path: /opt/uat/src/
       name: registry.devops4u.xyz/pythonapp8:v1
       tag: v1
       push: yes
       source: build
      vars:
        ansible_python_interpreter:  /usr/bin/python3
    - name:  DEPLOYMENT STATUS
      become_user: root
      shell: sudo kubectl get deployment,pods,rs 
      register: getdeploy
    - debug: msg="{{ getdeploy.stdout_lines }}"
    - name: Search for all running pods
      kubernetes.core.k8s_info:
          kind: Pod
          namespace: default
          field_selectors:
            - status.phase=Running
      register: listpodd
    - name: Flatten the complex object
      ansible.builtin.set_fact:
        paths: "{{ lookup('ansible.utils.to_paths', listpodd ) }}"
  

